services:
    Github\Client:
        arguments:
            - '@Github\HttpClient\Builder'

    Github\HttpClient\Builder:
        arguments:
            - '@?Http\Client\HttpClient'
            - '@?Http\Message\RequestFactory'
            - '@?Http\Message\StreamFactory'
