security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    role_hierarchy:
        ROLE_LABEL: ROLE_USER
        ROLE_FILTER: ROLE_USER
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\Authenticator\GithubAuthenticator
            entry_point: App\Security\Authenticator\GithubAuthenticator
            logout:
                path: oauth_logout
                target: home

    access_control:
        - { path: ^/oauth/login, roles: PUBLIC_ACCESS }
        - { path: ^/pull-requests, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/notifications, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/user, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
