twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        website_url: 'https://%env(HTTP_HOST)%'

when@test:
    twig:
        strict_variables: true
