twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        enableDarkTheme: '%env(bool:ENABLE_DARK_THEME)%'
        reloadOnFocus: '%env(bool:RELOAD_ON_FOCUS)%'
        reloadEvery: '%env(int:RELOAD_EVERY)%'
        useMode: '%env(USE_MODE)%'
