ajax_notif_reload:
    path: /reload/notification.html
    controller: App\Controller\ReloadNotificationController
    methods: [GET]

ajax_notif_mark_as_read:
    path: /notification/mark-as-read/{threadId}
    controller: App\Controller\MarkAsReadNotificationController
    methods: [POST]
    requirements:
        threadId: \d+
