oauth_login:
    path: /oauth/login
    controller: App\Controller\OAuth\LoginController
    methods: [GET]

oauth_logout:
    path: /oauth/logout
    methods: [GET]

oauth_callback_url:
    path: /oauth/callback-url
    methods: [GET]
