version: '3.5'

services:
    nginx:
        ports:
            - "${HTTP_PORT:-8011}:80"

    mysql:
        env_file:
            - ../.env.local
        ports:
            - "${MYSQL_PORT:-3310}:3306"

    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - "${ADMINER_PORT:-8012}:8080"
