version: '3.5'

services:
    nginx:
        environment:
            VIRTUAL_HOST: ${DOMAINS}
            LETSENCRYPT_HOST: ${DOMAINS}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
        networks:
            - default
            - github_gui

    php:
        networks:
            default:
            github_gui:
                aliases:
                    - "github_gui_php"

    mysql:
        networks:
            - default
            - github_gui

networks:
    github_gui:
    default:
        external:
            name: ${NETWORK}
