version: '3.5'

services:
    nginx:
        environment:
            VIRTUAL_HOST: ${DOMAINS}
            LETSENCRYPT_HOST: ${DOMAINS}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
        networks:
            - default
            - github_gui
        restart: "unless-stopped"

    php:
        networks:
            default:
            github_gui:
                aliases:
                    - "github_gui_php"
        restart: "unless-stopped"

    database:
        networks:
            default:
            github_gui:
                aliases:
                    - "github_gui_mysql"
        restart: "unless-stopped"

networks:
    github_gui:
    default:
        external:
            name: ${NETWORK}
