version: '3.5'

services:
    nginx:
        environment:
            VIRTUAL_HOST: ${DOMAINS}
            LETSENCRYPT_HOST: ${DOMAINS}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

    mysql:
        env_file:
            - ../.env
networks:
    default:
        external:
            name: ${NETWORK}
