parameters:

services:
    _defaults:
        autowire: true
        bind:
            $githubAuthMethod: '%env(GITHUB_AUTH_METHOD)%'
            $githubUsername: '%env(GITHUB_USERNAME)%'
            $githubPassword: '%env(GITHUB_PASSWORD)%'
            $githubToken: '%env(GITHUB_TOKEN)%'
            $githubRepos: '%env(json:GITHUB_REPOS)%'

    App\Controller\PullRequestController:
        public: true

    App\Service\Github\PullRequestService: ~
