parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        App\Model\Doctrine\Type\AbstractEnumType:
            tags: [ 'app.doctrine.type.enum' ]

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Enum/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]
