parameters:

services:
    _defaults:
        autowire: true
        bind:
            $githubAuthMethod: '%env(GITHUB_AUTH_METHOD)%'
            $githubUsername: '%env(GITHUB_USERNAME)%'
            $githubPassword: '%env(GITHUB_PASSWORD)%'
            $githubToken: '%env(GITHUB_TOKEN)%'
            $githubRepos: '%env(json:GITHUB_REPOS)%'
            $githubLabelsReviewNeeded: '%env(json:GITHUB_LABELS_REVIEW_NEEDED)%'
            $githubLabelsChangedRequested: '%env(json:GITHUB_LABELS_CHANGES_REQUESTED)%'
            $githubLabelsAccepted: '%env(json:GITHUB_LABELS_ACCEPTED)%'
            $githubLabelsWip: '%env(json:GITHUB_LABELS_WIP)%'
            $githubBranchsColors: '%env(json:GITHUB_BRANCHS_COLORS)%'
            $githubBranchDefaultColor: '%env(GITHUB_BRANCH_DEFAULT_COLOR)%'
            $githubFilters: '%env(json:GITHUB_FILTERS)%'
            $useLabels: '%env(bool:USE_LABELS)%'
            $useFilters: '%env(bool:USE_FILTERS)%'
            $githubExcludeReasons: '%env(json:GITHUB_EXCLUDE_REASONS)%'

    App\Controller\PullRequestController:
        public: true

    App\Service\Github\PullRequestLabelService: ~
    App\Service\Github\PullRequestFilterService: ~
    App\Service\Github\NotificationService: ~
    App\Service\Github\GithubClientService: ~
